### PR TITLE
Add static bearing holder, drop-in replacement for 7.5mm Veichu VCN310 BTU

### PR DESCRIPTION
**Pull request by Wimads**

### CODE REVIEW

**Comment by finrod09** [comment]
I would suggest adding your mod to the main mods readme, perhaps right below the Veichu bearings.

**Comment by Wimads** [comment]
> I would suggest adding your mod to the main mods readme, perhaps right below the Veichu bearings.

Ah, right, yeah makes sense.

**Comment by Wimads** [comment]
Ok, sorry for all the commit spam. This should be ready to merge from my side now :P Over to bkb team ;)

**Comment by bstiq** [comment]
🥳

**Pull request merged**
