### PR TITLE
feat: 3x5+3 low file variants

### PR DESCRIPTION
**Pull request by gagregrog**
This PR adds a few variations I used when doing a recent Charybdis 3x5+3 handwire build. I thought they may be helpful to others, so figure'd I'd make the PR in case you wanted to use any of it.

Notable modifications:

<details><summary>1. `3x5+3_low_clipped.stl` is a variant of `3x5_3 low v16.stl` which removes the extra threaded insert at the base near the trackball opening. I found that this got in the way when adding the trackball, and it didn't seem necessary for the plate mounting.</summary> 

image

</details>

<details><summary>2. `flat_plate.stl` is a base plate to be used with `3x5+3_low_clipped.stl` that is a bit taller than normal to allow you to use the Charybdis without any tenting. The additional height is needed to offset the trackball mount.</summary>

image

image

image

</details>

<details><summary>3. `mcu_holder.stl` is what it sounds like. A holder that holds an MCU (designed for a kb2040 but should fit other pro-micro footprints as well), trrs jack, and 6mm reset button. Fits the modified profile of the `3x5+3_low_clipped.stl`.</summary>

image

image

image

</details>

<details><summary>4. `adapter_v2_bottom_adns-9800.stl` modifies `adapter_v2_bottom` to accept the adns-9800 sensor PCB found [here](https://www.tindie.com/products/jkicklighter/adns-9800-laser-motion-sensor)</summary>

image

image

</details>

<details><summary>5. `adapter_v2_bottom_pmw3389.stl` modifies `adapter_v2_bottom` to accept the pmw-3389 sensor PCB found [here](https://www.tindie.com/products/jkicklighter/pmw3389-motion-sensor)</summary>

image

image

</details>

<details><summary>6. `3x5+3_low_tent_plate.stl` is an additional plate for the `tenting-with-wrist-pads` mod. This plate fits the 3x5+3 variant (specifically the variant I've uploaded in this PR, but the original version too. It's like the `flat_plate`, except it is thinner and contains the required mounts for the tent mod.</summary>

image

image

</details>

<details><summary>7. `pads-arm-extended.stl` is a modification of `pads-arm.stl` for the `tenting-with-wrist-pads` mod which extends it by 50mm.</summary>

image

</details>

<details><summary>8. `pads-base-short.stl` is a modificaton of `pads-arm.stl` for the `tenting-with-wrist-pads` mod which lowers the pad height by 5mm.</summary>

image

</details>

### CODE REVIEW

**Comment by bstiq** [comment]
Hello,

That's quite a lot of design, thanks !

I moved the bearing adapters to the `mods` folder.

A few questions:
- If I understand correctly, `files/mods/tenting-stand-with-wrist-pads/` is compatible only with the 3x5-lowtrackball version ? If that is the case, can you move the files from the mods folder to the lowtrackball folder.
- Could you also modify the 3x5+3's readme with maybe some picture examples of your designs, and some text describing the new files you added


Regards,

**Comment by gagregrog** [comment]
Hey Quentin,

`files/mods/tenting-stand-with-wrist-pads/` already existed and appears to have been created by @alexeyatbluescape. As I understand it the tent should work for any variant, but there were two custom (optional) plates that were originally created specifically for the Scylla and Charybdis 4x6. My addition here introduces a few more options for the accessories, and a new custom plate that fits the 3x5+3_low. Considering that I think it makes more sense to leave it where it is, but I'll defer to your judgement on that.

And sure thing, I can update the README

**Comment by gagregrog** [comment]
OK, docs and pics updated 😃

**Comment by bstiq** [comment]
Ah, I see.
The point was to keep the non-official-BKB stuff in the `mods` folder. That's better, thanks.

**Comment by bstiq** [comment]
I just compressed the images a bit, from PNG~15-20Mb to JPG~1Mb, keep the repo light-ish to clone.

I'll merge it now, thanks for your work !
PS those tents look sick

Regards,

**Pull request merged**
